### ISSUE TITLE
Add support for Cloaks+ and Cosmetica capes

### ISSUE THREAD

**Issue by Nonstopgaming75** [GeyserMC/ThirdPartyCosmetics#2]
### What feature do you want to see added?

Hi I already saw that geyser allows third party capes like optifine and Minecraftcapes.
I wanted to request the implementation of cloaks+ capes a free mod that gives u a cloak for free and also other decorations.
The way they do it is exactly like optifine with their own server hosting the cape that gets loaded on the client of choice ( u need optifine to use the mod) and it supports lunar and other clients.
Their site:
https://cloaksplus.com/

Same thing goes for cosmetica
(Someone requested this already:
GeyserMC/ThirdPartyCosmetics#3 )

### Are there any alternatives?

Couldn’t find a workaround

**Comment by rtm516** [comment]
Due to how Cloaks+ installs it's self (edits the system hosts file) we are not comfortable with adding it to an official extension.
