### ISSUE TITLE
High resolution capes won't get displayed correctly.

### ISSUE THREAD

**Issue by Fridtjof-DE** [GeyserMC/ThirdPartyCosmetics#5]
### Describe the bug

High resolution capes won't get displayed correctly on Bedrock clients because the original image just gets cropped out to the default resolution.

### To Reproduce

1. Join a server that allows third party capes and look at a player wearing a hd cape from LabyMod or OptiFine in example.

### Expected behaviour

Capes should be display correctly or if not possible at least be scaled down.

### Screenshots / Videos

Bedrock:
![Screenshot (4)](https://github.com/GeyserMC/Geyser/assets/38737231/cb2882e9-e0f3-459c-b539-2c037018739e)

Java:
![2024-01-02_02 52 10](https://github.com/GeyserMC/Geyser/assets/38737231/c97623dd-b08f-4cb5-9523-b754634ae7c6)

### Geyser Version

2.2.0-SNAPSHOT (git-master-46bde0c)

### Minecraft: Bedrock Edition Device/Version

any

**Comment by rtm516** [comment]
I believe this is a bedrock limitation and nothing we can do but downscale the capes, could you provide an example texture for it?
Ive tried testing with one I found online and it didn't even show up on the client

**Comment by rtm516** [comment]
This was fixed in https://github.com/GeyserMC/ThirdPartyCosmetics/commit/f6e00d6877c46e9a4f8c73a62fca09536c6f9d84 / https://github.com/GeyserMC/ThirdPartyCosmetics/pull/11
